'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DemoTimbreFINKOK
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://facturacion.finkok.com/stamp", ConfigurationName:="DemoTimbreFINKOK.Application")>  _
    Public Interface Application
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación sign_stamp no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="sign_stamp", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function sign_stamp(ByVal request As DemoTimbreFINKOK.sign_stamp1) As DemoTimbreFINKOK.sign_stampResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="sign_stamp", ReplyAction:="*")>  _
        Function sign_stampAsync(ByVal request As DemoTimbreFINKOK.sign_stamp1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.sign_stampResponse1)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación stamped no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="stamped", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function stamped(ByVal request As DemoTimbreFINKOK.stamped1) As DemoTimbreFINKOK.stampedResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="stamped", ReplyAction:="*")>  _
        Function stampedAsync(ByVal request As DemoTimbreFINKOK.stamped1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.stampedResponse1)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación stamp no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="stamp", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function stamp(ByVal request As DemoTimbreFINKOK.stamp1) As DemoTimbreFINKOK.stampResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="stamp", ReplyAction:="*")>  _
        Function stampAsync(ByVal request As DemoTimbreFINKOK.stamp1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.stampResponse1)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación stamp_async no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="stamp_async", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function stamp_async(ByVal request As DemoTimbreFINKOK.stamp_async1) As DemoTimbreFINKOK.stamp_asyncResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="stamp_async", ReplyAction:="*")>  _
        Function stamp_asyncAsync(ByVal request As DemoTimbreFINKOK.stamp_async1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.stamp_asyncResponse1)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación query_pending no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="query_pending", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function query_pending(ByVal request As DemoTimbreFINKOK.query_pending1) As DemoTimbreFINKOK.query_pendingResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="query_pending", ReplyAction:="*")>  _
        Function query_pendingAsync(ByVal request As DemoTimbreFINKOK.query_pending1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.query_pendingResponse1)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación get_pdf no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="get_pdf", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_pdf(ByVal request As DemoTimbreFINKOK.get_pdf1) As DemoTimbreFINKOK.get_pdfResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="get_pdf", ReplyAction:="*")>  _
        Function get_pdfAsync(ByVal request As DemoTimbreFINKOK.get_pdf1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.get_pdfResponse1)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación quick_stamp no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="quick_stamp", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function quick_stamp(ByVal request As DemoTimbreFINKOK.quick_stamp1) As DemoTimbreFINKOK.quick_stampResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="quick_stamp", ReplyAction:="*")>  _
        Function quick_stampAsync(ByVal request As DemoTimbreFINKOK.quick_stamp1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.quick_stampResponse1)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación get_result_async no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="get_result_async", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function get_result_async(ByVal request As DemoTimbreFINKOK.get_result_async1) As DemoTimbreFINKOK.get_result_asyncResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="get_result_async", ReplyAction:="*")>  _
        Function get_result_asyncAsync(ByVal request As DemoTimbreFINKOK.get_result_async1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.get_result_asyncResponse1)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class sign_stamp
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private xmlField() As Byte
        
        Private usernameField As String
        
        Private passwordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true, Order:=0)>  _
        Public Property xml() As Byte()
            Get
                Return Me.xmlField
            End Get
            Set
                Me.xmlField = value
                Me.RaisePropertyChanged("xml")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
                Me.RaisePropertyChanged("username")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://facturacion.finkok.com/servicios/async")>  _
    Partial Public Class AcuseRecepcionAsync
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private uUIDField As String
        
        Private rfcProvCertifField As String
        
        Private noCertificadoSATField As String
        
        Private codEstatusField As String
        
        Private faultstringField As String
        
        Private faultcodeField As String
        
        Private fileField() As Byte
        
        Private satSealField As String
        
        Private incidenciasField() As Incidencia
        
        Private fechaTimbradoField As System.Nullable(Of Date)
        
        Private fechaTimbradoFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
                Me.RaisePropertyChanged("UUID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property RfcProvCertif() As String
            Get
                Return Me.rfcProvCertifField
            End Get
            Set
                Me.rfcProvCertifField = value
                Me.RaisePropertyChanged("RfcProvCertif")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property NoCertificadoSAT() As String
            Get
                Return Me.noCertificadoSATField
            End Get
            Set
                Me.noCertificadoSATField = value
                Me.RaisePropertyChanged("NoCertificadoSAT")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property CodEstatus() As String
            Get
                Return Me.codEstatusField
            End Get
            Set
                Me.codEstatusField = value
                Me.RaisePropertyChanged("CodEstatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property faultstring() As String
            Get
                Return Me.faultstringField
            End Get
            Set
                Me.faultstringField = value
                Me.RaisePropertyChanged("faultstring")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
        Public Property faultcode() As String
            Get
                Return Me.faultcodeField
            End Get
            Set
                Me.faultcodeField = value
                Me.RaisePropertyChanged("faultcode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true, Order:=6)>  _
        Public Property file() As Byte()
            Get
                Return Me.fileField
            End Get
            Set
                Me.fileField = value
                Me.RaisePropertyChanged("file")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=7)>  _
        Public Property SatSeal() As String
            Get
                Return Me.satSealField
            End Get
            Set
                Me.satSealField = value
                Me.RaisePropertyChanged("SatSeal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true, Order:=8),  _
         System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="apps.services.soap.core.views")>  _
        Public Property Incidencias() As Incidencia()
            Get
                Return Me.incidenciasField
            End Get
            Set
                Me.incidenciasField = value
                Me.RaisePropertyChanged("Incidencias")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=9)>  _
        Public Property FechaTimbrado() As System.Nullable(Of Date)
            Get
                Return Me.fechaTimbradoField
            End Get
            Set
                Me.fechaTimbradoField = value
                Me.RaisePropertyChanged("FechaTimbrado")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FechaTimbradoSpecified() As Boolean
            Get
                Return Me.fechaTimbradoFieldSpecified
            End Get
            Set
                Me.fechaTimbradoFieldSpecified = value
                Me.RaisePropertyChanged("FechaTimbradoSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class Incidencia
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idIncidenciaField As String
        
        Private rfcEmisorField As String
        
        Private uuidField As String
        
        Private codigoErrorField As String
        
        Private workProcessIdField As String
        
        Private mensajeIncidenciaField As String
        
        Private extraInfoField As String
        
        Private noCertificadoPacField As String
        
        Private fechaRegistroField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property IdIncidencia() As String
            Get
                Return Me.idIncidenciaField
            End Get
            Set
                Me.idIncidenciaField = value
                Me.RaisePropertyChanged("IdIncidencia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property RfcEmisor() As String
            Get
                Return Me.rfcEmisorField
            End Get
            Set
                Me.rfcEmisorField = value
                Me.RaisePropertyChanged("RfcEmisor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property Uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
                Me.RaisePropertyChanged("Uuid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property CodigoError() As String
            Get
                Return Me.codigoErrorField
            End Get
            Set
                Me.codigoErrorField = value
                Me.RaisePropertyChanged("CodigoError")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property WorkProcessId() As String
            Get
                Return Me.workProcessIdField
            End Get
            Set
                Me.workProcessIdField = value
                Me.RaisePropertyChanged("WorkProcessId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
        Public Property MensajeIncidencia() As String
            Get
                Return Me.mensajeIncidenciaField
            End Get
            Set
                Me.mensajeIncidenciaField = value
                Me.RaisePropertyChanged("MensajeIncidencia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=6)>  _
        Public Property ExtraInfo() As String
            Get
                Return Me.extraInfoField
            End Get
            Set
                Me.extraInfoField = value
                Me.RaisePropertyChanged("ExtraInfo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=7)>  _
        Public Property NoCertificadoPac() As String
            Get
                Return Me.noCertificadoPacField
            End Get
            Set
                Me.noCertificadoPacField = value
                Me.RaisePropertyChanged("NoCertificadoPac")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=8)>  _
        Public Property FechaRegistro() As String
            Get
                Return Me.fechaRegistroField
            End Get
            Set
                Me.fechaRegistroField = value
                Me.RaisePropertyChanged("FechaRegistro")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class get_result_asyncResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private get_result_asyncResultField As AcuseRecepcionAsync
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property get_result_asyncResult() As AcuseRecepcionAsync
            Get
                Return Me.get_result_asyncResultField
            End Get
            Set
                Me.get_result_asyncResultField = value
                Me.RaisePropertyChanged("get_result_asyncResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class get_result_async
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idField As String
        
        Private usernameField As String
        
        Private passwordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
                Me.RaisePropertyChanged("username")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class quick_stampResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private quick_stampResultField As AcuseRecepcionCFDI
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property quick_stampResult() As AcuseRecepcionCFDI
            Get
                Return Me.quick_stampResultField
            End Get
            Set
                Me.quick_stampResultField = value
                Me.RaisePropertyChanged("quick_stampResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class AcuseRecepcionCFDI
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private xmlField As String
        
        Private uUIDField As String
        
        Private faultstringField As String
        
        Private fechaField As String
        
        Private codEstatusField As String
        
        Private faultcodeField As String
        
        Private satSealField As String
        
        Private incidenciasField() As Incidencia
        
        Private noCertificadoSATField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property xml() As String
            Get
                Return Me.xmlField
            End Get
            Set
                Me.xmlField = value
                Me.RaisePropertyChanged("xml")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
                Me.RaisePropertyChanged("UUID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property faultstring() As String
            Get
                Return Me.faultstringField
            End Get
            Set
                Me.faultstringField = value
                Me.RaisePropertyChanged("faultstring")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property Fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
                Me.RaisePropertyChanged("Fecha")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property CodEstatus() As String
            Get
                Return Me.codEstatusField
            End Get
            Set
                Me.codEstatusField = value
                Me.RaisePropertyChanged("CodEstatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
        Public Property faultcode() As String
            Get
                Return Me.faultcodeField
            End Get
            Set
                Me.faultcodeField = value
                Me.RaisePropertyChanged("faultcode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=6)>  _
        Public Property SatSeal() As String
            Get
                Return Me.satSealField
            End Get
            Set
                Me.satSealField = value
                Me.RaisePropertyChanged("SatSeal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true, Order:=7)>  _
        Public Property Incidencias() As Incidencia()
            Get
                Return Me.incidenciasField
            End Get
            Set
                Me.incidenciasField = value
                Me.RaisePropertyChanged("Incidencias")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=8)>  _
        Public Property NoCertificadoSAT() As String
            Get
                Return Me.noCertificadoSATField
            End Get
            Set
                Me.noCertificadoSATField = value
                Me.RaisePropertyChanged("NoCertificadoSAT")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class quick_stamp
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private xmlField() As Byte
        
        Private usernameField As String
        
        Private passwordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true, Order:=0)>  _
        Public Property xml() As Byte()
            Get
                Return Me.xmlField
            End Get
            Set
                Me.xmlField = value
                Me.RaisePropertyChanged("xml")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
                Me.RaisePropertyChanged("username")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class PDFResult
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private pdfField() As Byte
        
        Private errorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true, Order:=0)>  _
        Public Property pdf() As Byte()
            Get
                Return Me.pdfField
            End Get
            Set
                Me.pdfField = value
                Me.RaisePropertyChanged("pdf")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
                Me.RaisePropertyChanged("error")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class get_pdfResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private get_pdfResultField As PDFResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property get_pdfResult() As PDFResult
            Get
                Return Me.get_pdfResultField
            End Get
            Set
                Me.get_pdfResultField = value
                Me.RaisePropertyChanged("get_pdfResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class get_pdf
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private uuidField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
                Me.RaisePropertyChanged("username")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
                Me.RaisePropertyChanged("uuid")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class QueryPendingResult
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private statusField As String
        
        Private xmlField As String
        
        Private uuidField As String
        
        Private uuid_statusField As String
        
        Private next_attemptField As String
        
        Private attemptsField As String
        
        Private errorField As String
        
        Private dateField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property xml() As String
            Get
                Return Me.xmlField
            End Get
            Set
                Me.xmlField = value
                Me.RaisePropertyChanged("xml")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
                Me.RaisePropertyChanged("uuid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property uuid_status() As String
            Get
                Return Me.uuid_statusField
            End Get
            Set
                Me.uuid_statusField = value
                Me.RaisePropertyChanged("uuid_status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=4)>  _
        Public Property next_attempt() As String
            Get
                Return Me.next_attemptField
            End Get
            Set
                Me.next_attemptField = value
                Me.RaisePropertyChanged("next_attempt")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
        Public Property attempts() As String
            Get
                Return Me.attemptsField
            End Get
            Set
                Me.attemptsField = value
                Me.RaisePropertyChanged("attempts")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=6)>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
                Me.RaisePropertyChanged("error")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=7)>  _
        Public Property [date]() As String
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
                Me.RaisePropertyChanged("date")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class query_pendingResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private query_pendingResultField As QueryPendingResult
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property query_pendingResult() As QueryPendingResult
            Get
                Return Me.query_pendingResultField
            End Get
            Set
                Me.query_pendingResultField = value
                Me.RaisePropertyChanged("query_pendingResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class query_pending
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private uuidField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
                Me.RaisePropertyChanged("username")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
                Me.RaisePropertyChanged("uuid")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="apps.services.soap.core.views")>  _
    Partial Public Class ResultAsync
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private statusField As String
        
        Private incidenciasField() As Incidencia
        
        Private idField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true, Order:=1)>  _
        Public Property Incidencias() As Incidencia()
            Get
                Return Me.incidenciasField
            End Get
            Set
                Me.incidenciasField = value
                Me.RaisePropertyChanged("Incidencias")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("id")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class stamp_asyncResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private stamp_asyncResultField As ResultAsync
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property stamp_asyncResult() As ResultAsync
            Get
                Return Me.stamp_asyncResultField
            End Get
            Set
                Me.stamp_asyncResultField = value
                Me.RaisePropertyChanged("stamp_asyncResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class stamp_async
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private fileField() As Byte
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private ctypeField As stamp_async_ctypeType
        
        Private ctypeFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", Order:=0)>  _
        Public Property file() As Byte()
            Get
                Return Me.fileField
            End Get
            Set
                Me.fileField = value
                Me.RaisePropertyChanged("file")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
                Me.RaisePropertyChanged("username")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property [ctype]() As stamp_async_ctypeType
            Get
                Return Me.ctypeField
            End Get
            Set
                Me.ctypeField = value
                Me.RaisePropertyChanged("ctype")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ctypeSpecified() As Boolean
            Get
                Return Me.ctypeFieldSpecified
            End Get
            Set
                Me.ctypeFieldSpecified = value
                Me.RaisePropertyChanged("ctypeSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Public Enum stamp_async_ctypeType
        
        '''<remarks/>
        zip
        
        '''<remarks/>
        gzip
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class stampResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private stampResultField As AcuseRecepcionCFDI
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property stampResult() As AcuseRecepcionCFDI
            Get
                Return Me.stampResultField
            End Get
            Set
                Me.stampResultField = value
                Me.RaisePropertyChanged("stampResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class stamp
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private xmlField() As Byte
        
        Private usernameField As String
        
        Private passwordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true, Order:=0)>  _
        Public Property xml() As Byte()
            Get
                Return Me.xmlField
            End Get
            Set
                Me.xmlField = value
                Me.RaisePropertyChanged("xml")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
                Me.RaisePropertyChanged("username")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class stampedResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private stampedResultField As AcuseRecepcionCFDI
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property stampedResult() As AcuseRecepcionCFDI
            Get
                Return Me.stampedResultField
            End Get
            Set
                Me.stampedResultField = value
                Me.RaisePropertyChanged("stampedResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class stamped
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private xmlField() As Byte
        
        Private usernameField As String
        
        Private passwordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true, Order:=0)>  _
        Public Property xml() As Byte()
            Get
                Return Me.xmlField
            End Get
            Set
                Me.xmlField = value
                Me.RaisePropertyChanged("xml")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=1)>  _
        Public Property username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
                Me.RaisePropertyChanged("username")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://facturacion.finkok.com/stamp")>  _
    Partial Public Class sign_stampResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private sign_stampResultField As AcuseRecepcionCFDI
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property sign_stampResult() As AcuseRecepcionCFDI
            Get
                Return Me.sign_stampResultField
            End Get
            Set
                Me.sign_stampResultField = value
                Me.RaisePropertyChanged("sign_stampResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class sign_stamp1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public sign_stamp As DemoTimbreFINKOK.sign_stamp
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal sign_stamp As DemoTimbreFINKOK.sign_stamp)
            MyBase.New
            Me.sign_stamp = sign_stamp
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class sign_stampResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public sign_stampResponse As DemoTimbreFINKOK.sign_stampResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal sign_stampResponse As DemoTimbreFINKOK.sign_stampResponse)
            MyBase.New
            Me.sign_stampResponse = sign_stampResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class stamped1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public stamped As DemoTimbreFINKOK.stamped
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal stamped As DemoTimbreFINKOK.stamped)
            MyBase.New
            Me.stamped = stamped
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class stampedResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public stampedResponse As DemoTimbreFINKOK.stampedResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal stampedResponse As DemoTimbreFINKOK.stampedResponse)
            MyBase.New
            Me.stampedResponse = stampedResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class stamp1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public stamp As DemoTimbreFINKOK.stamp
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal stamp As DemoTimbreFINKOK.stamp)
            MyBase.New
            Me.stamp = stamp
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class stampResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public stampResponse As DemoTimbreFINKOK.stampResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal stampResponse As DemoTimbreFINKOK.stampResponse)
            MyBase.New
            Me.stampResponse = stampResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class stamp_async1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public stamp_async As DemoTimbreFINKOK.stamp_async
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal stamp_async As DemoTimbreFINKOK.stamp_async)
            MyBase.New
            Me.stamp_async = stamp_async
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class stamp_asyncResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public stamp_asyncResponse As DemoTimbreFINKOK.stamp_asyncResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal stamp_asyncResponse As DemoTimbreFINKOK.stamp_asyncResponse)
            MyBase.New
            Me.stamp_asyncResponse = stamp_asyncResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class query_pending1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public query_pending As DemoTimbreFINKOK.query_pending
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal query_pending As DemoTimbreFINKOK.query_pending)
            MyBase.New
            Me.query_pending = query_pending
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class query_pendingResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public query_pendingResponse As DemoTimbreFINKOK.query_pendingResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal query_pendingResponse As DemoTimbreFINKOK.query_pendingResponse)
            MyBase.New
            Me.query_pendingResponse = query_pendingResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class get_pdf1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public get_pdf As DemoTimbreFINKOK.get_pdf
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal get_pdf As DemoTimbreFINKOK.get_pdf)
            MyBase.New
            Me.get_pdf = get_pdf
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class get_pdfResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public get_pdfResponse As DemoTimbreFINKOK.get_pdfResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal get_pdfResponse As DemoTimbreFINKOK.get_pdfResponse)
            MyBase.New
            Me.get_pdfResponse = get_pdfResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class quick_stamp1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public quick_stamp As DemoTimbreFINKOK.quick_stamp
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal quick_stamp As DemoTimbreFINKOK.quick_stamp)
            MyBase.New
            Me.quick_stamp = quick_stamp
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class quick_stampResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public quick_stampResponse As DemoTimbreFINKOK.quick_stampResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal quick_stampResponse As DemoTimbreFINKOK.quick_stampResponse)
            MyBase.New
            Me.quick_stampResponse = quick_stampResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class get_result_async1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public get_result_async As DemoTimbreFINKOK.get_result_async
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal get_result_async As DemoTimbreFINKOK.get_result_async)
            MyBase.New
            Me.get_result_async = get_result_async
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class get_result_asyncResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://facturacion.finkok.com/stamp", Order:=0)>  _
        Public get_result_asyncResponse As DemoTimbreFINKOK.get_result_asyncResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal get_result_asyncResponse As DemoTimbreFINKOK.get_result_asyncResponse)
            MyBase.New
            Me.get_result_asyncResponse = get_result_asyncResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ApplicationChannel
        Inherits DemoTimbreFINKOK.Application, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ApplicationClient
        Inherits System.ServiceModel.ClientBase(Of DemoTimbreFINKOK.Application)
        Implements DemoTimbreFINKOK.Application
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_sign_stamp(ByVal request As DemoTimbreFINKOK.sign_stamp1) As DemoTimbreFINKOK.sign_stampResponse1 Implements DemoTimbreFINKOK.Application.sign_stamp
            Return MyBase.Channel.sign_stamp(request)
        End Function
        
        Public Function sign_stamp(ByVal sign_stamp1 As DemoTimbreFINKOK.sign_stamp) As DemoTimbreFINKOK.sign_stampResponse
            Dim inValue As DemoTimbreFINKOK.sign_stamp1 = New DemoTimbreFINKOK.sign_stamp1()
            inValue.sign_stamp = sign_stamp1
            Dim retVal As DemoTimbreFINKOK.sign_stampResponse1 = CType(Me,DemoTimbreFINKOK.Application).sign_stamp(inValue)
            Return retVal.sign_stampResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_sign_stampAsync(ByVal request As DemoTimbreFINKOK.sign_stamp1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.sign_stampResponse1) Implements DemoTimbreFINKOK.Application.sign_stampAsync
            Return MyBase.Channel.sign_stampAsync(request)
        End Function
        
        Public Function sign_stampAsync(ByVal sign_stamp As DemoTimbreFINKOK.sign_stamp) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.sign_stampResponse1)
            Dim inValue As DemoTimbreFINKOK.sign_stamp1 = New DemoTimbreFINKOK.sign_stamp1()
            inValue.sign_stamp = sign_stamp
            Return CType(Me,DemoTimbreFINKOK.Application).sign_stampAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_stamped(ByVal request As DemoTimbreFINKOK.stamped1) As DemoTimbreFINKOK.stampedResponse1 Implements DemoTimbreFINKOK.Application.stamped
            Return MyBase.Channel.stamped(request)
        End Function
        
        Public Function stamped(ByVal stamped1 As DemoTimbreFINKOK.stamped) As DemoTimbreFINKOK.stampedResponse
            Dim inValue As DemoTimbreFINKOK.stamped1 = New DemoTimbreFINKOK.stamped1()
            inValue.stamped = stamped1
            Dim retVal As DemoTimbreFINKOK.stampedResponse1 = CType(Me,DemoTimbreFINKOK.Application).stamped(inValue)
            Return retVal.stampedResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_stampedAsync(ByVal request As DemoTimbreFINKOK.stamped1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.stampedResponse1) Implements DemoTimbreFINKOK.Application.stampedAsync
            Return MyBase.Channel.stampedAsync(request)
        End Function
        
        Public Function stampedAsync(ByVal stamped As DemoTimbreFINKOK.stamped) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.stampedResponse1)
            Dim inValue As DemoTimbreFINKOK.stamped1 = New DemoTimbreFINKOK.stamped1()
            inValue.stamped = stamped
            Return CType(Me,DemoTimbreFINKOK.Application).stampedAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_stamp(ByVal request As DemoTimbreFINKOK.stamp1) As DemoTimbreFINKOK.stampResponse1 Implements DemoTimbreFINKOK.Application.stamp
            Return MyBase.Channel.stamp(request)
        End Function
        
        Public Function stamp(ByVal stamp1 As DemoTimbreFINKOK.stamp) As DemoTimbreFINKOK.stampResponse
            Dim inValue As DemoTimbreFINKOK.stamp1 = New DemoTimbreFINKOK.stamp1()
            inValue.stamp = stamp1
            Dim retVal As DemoTimbreFINKOK.stampResponse1 = CType(Me,DemoTimbreFINKOK.Application).stamp(inValue)
            Return retVal.stampResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_stampAsync(ByVal request As DemoTimbreFINKOK.stamp1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.stampResponse1) Implements DemoTimbreFINKOK.Application.stampAsync
            Return MyBase.Channel.stampAsync(request)
        End Function
        
        Public Function stampAsync(ByVal stamp As DemoTimbreFINKOK.stamp) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.stampResponse1)
            Dim inValue As DemoTimbreFINKOK.stamp1 = New DemoTimbreFINKOK.stamp1()
            inValue.stamp = stamp
            Return CType(Me,DemoTimbreFINKOK.Application).stampAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_stamp_async(ByVal request As DemoTimbreFINKOK.stamp_async1) As DemoTimbreFINKOK.stamp_asyncResponse1 Implements DemoTimbreFINKOK.Application.stamp_async
            Return MyBase.Channel.stamp_async(request)
        End Function
        
        Public Function stamp_async(ByVal stamp_async1 As DemoTimbreFINKOK.stamp_async) As DemoTimbreFINKOK.stamp_asyncResponse
            Dim inValue As DemoTimbreFINKOK.stamp_async1 = New DemoTimbreFINKOK.stamp_async1()
            inValue.stamp_async = stamp_async1
            Dim retVal As DemoTimbreFINKOK.stamp_asyncResponse1 = CType(Me,DemoTimbreFINKOK.Application).stamp_async(inValue)
            Return retVal.stamp_asyncResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_stamp_asyncAsync(ByVal request As DemoTimbreFINKOK.stamp_async1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.stamp_asyncResponse1) Implements DemoTimbreFINKOK.Application.stamp_asyncAsync
            Return MyBase.Channel.stamp_asyncAsync(request)
        End Function
        
        Public Function stamp_asyncAsync(ByVal stamp_async As DemoTimbreFINKOK.stamp_async) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.stamp_asyncResponse1)
            Dim inValue As DemoTimbreFINKOK.stamp_async1 = New DemoTimbreFINKOK.stamp_async1()
            inValue.stamp_async = stamp_async
            Return CType(Me,DemoTimbreFINKOK.Application).stamp_asyncAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_query_pending(ByVal request As DemoTimbreFINKOK.query_pending1) As DemoTimbreFINKOK.query_pendingResponse1 Implements DemoTimbreFINKOK.Application.query_pending
            Return MyBase.Channel.query_pending(request)
        End Function
        
        Public Function query_pending(ByVal query_pending1 As DemoTimbreFINKOK.query_pending) As DemoTimbreFINKOK.query_pendingResponse
            Dim inValue As DemoTimbreFINKOK.query_pending1 = New DemoTimbreFINKOK.query_pending1()
            inValue.query_pending = query_pending1
            Dim retVal As DemoTimbreFINKOK.query_pendingResponse1 = CType(Me,DemoTimbreFINKOK.Application).query_pending(inValue)
            Return retVal.query_pendingResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_query_pendingAsync(ByVal request As DemoTimbreFINKOK.query_pending1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.query_pendingResponse1) Implements DemoTimbreFINKOK.Application.query_pendingAsync
            Return MyBase.Channel.query_pendingAsync(request)
        End Function
        
        Public Function query_pendingAsync(ByVal query_pending As DemoTimbreFINKOK.query_pending) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.query_pendingResponse1)
            Dim inValue As DemoTimbreFINKOK.query_pending1 = New DemoTimbreFINKOK.query_pending1()
            inValue.query_pending = query_pending
            Return CType(Me,DemoTimbreFINKOK.Application).query_pendingAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_get_pdf(ByVal request As DemoTimbreFINKOK.get_pdf1) As DemoTimbreFINKOK.get_pdfResponse1 Implements DemoTimbreFINKOK.Application.get_pdf
            Return MyBase.Channel.get_pdf(request)
        End Function
        
        Public Function get_pdf(ByVal get_pdf1 As DemoTimbreFINKOK.get_pdf) As DemoTimbreFINKOK.get_pdfResponse
            Dim inValue As DemoTimbreFINKOK.get_pdf1 = New DemoTimbreFINKOK.get_pdf1()
            inValue.get_pdf = get_pdf1
            Dim retVal As DemoTimbreFINKOK.get_pdfResponse1 = CType(Me,DemoTimbreFINKOK.Application).get_pdf(inValue)
            Return retVal.get_pdfResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_get_pdfAsync(ByVal request As DemoTimbreFINKOK.get_pdf1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.get_pdfResponse1) Implements DemoTimbreFINKOK.Application.get_pdfAsync
            Return MyBase.Channel.get_pdfAsync(request)
        End Function
        
        Public Function get_pdfAsync(ByVal get_pdf As DemoTimbreFINKOK.get_pdf) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.get_pdfResponse1)
            Dim inValue As DemoTimbreFINKOK.get_pdf1 = New DemoTimbreFINKOK.get_pdf1()
            inValue.get_pdf = get_pdf
            Return CType(Me,DemoTimbreFINKOK.Application).get_pdfAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_quick_stamp(ByVal request As DemoTimbreFINKOK.quick_stamp1) As DemoTimbreFINKOK.quick_stampResponse1 Implements DemoTimbreFINKOK.Application.quick_stamp
            Return MyBase.Channel.quick_stamp(request)
        End Function
        
        Public Function quick_stamp(ByVal quick_stamp1 As DemoTimbreFINKOK.quick_stamp) As DemoTimbreFINKOK.quick_stampResponse
            Dim inValue As DemoTimbreFINKOK.quick_stamp1 = New DemoTimbreFINKOK.quick_stamp1()
            inValue.quick_stamp = quick_stamp1
            Dim retVal As DemoTimbreFINKOK.quick_stampResponse1 = CType(Me,DemoTimbreFINKOK.Application).quick_stamp(inValue)
            Return retVal.quick_stampResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_quick_stampAsync(ByVal request As DemoTimbreFINKOK.quick_stamp1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.quick_stampResponse1) Implements DemoTimbreFINKOK.Application.quick_stampAsync
            Return MyBase.Channel.quick_stampAsync(request)
        End Function
        
        Public Function quick_stampAsync(ByVal quick_stamp As DemoTimbreFINKOK.quick_stamp) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.quick_stampResponse1)
            Dim inValue As DemoTimbreFINKOK.quick_stamp1 = New DemoTimbreFINKOK.quick_stamp1()
            inValue.quick_stamp = quick_stamp
            Return CType(Me,DemoTimbreFINKOK.Application).quick_stampAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_get_result_async(ByVal request As DemoTimbreFINKOK.get_result_async1) As DemoTimbreFINKOK.get_result_asyncResponse1 Implements DemoTimbreFINKOK.Application.get_result_async
            Return MyBase.Channel.get_result_async(request)
        End Function
        
        Public Function get_result_async(ByVal get_result_async1 As DemoTimbreFINKOK.get_result_async) As DemoTimbreFINKOK.get_result_asyncResponse
            Dim inValue As DemoTimbreFINKOK.get_result_async1 = New DemoTimbreFINKOK.get_result_async1()
            inValue.get_result_async = get_result_async1
            Dim retVal As DemoTimbreFINKOK.get_result_asyncResponse1 = CType(Me,DemoTimbreFINKOK.Application).get_result_async(inValue)
            Return retVal.get_result_asyncResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DemoTimbreFINKOK_Application_get_result_asyncAsync(ByVal request As DemoTimbreFINKOK.get_result_async1) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.get_result_asyncResponse1) Implements DemoTimbreFINKOK.Application.get_result_asyncAsync
            Return MyBase.Channel.get_result_asyncAsync(request)
        End Function
        
        Public Function get_result_asyncAsync(ByVal get_result_async As DemoTimbreFINKOK.get_result_async) As System.Threading.Tasks.Task(Of DemoTimbreFINKOK.get_result_asyncResponse1)
            Dim inValue As DemoTimbreFINKOK.get_result_async1 = New DemoTimbreFINKOK.get_result_async1()
            inValue.get_result_async = get_result_async
            Return CType(Me,DemoTimbreFINKOK.Application).get_result_asyncAsync(inValue)
        End Function
    End Class
End Namespace
